name: Bicep Build
description: Build an ARM template from Bicep main file

inputs:
  bicepFilePath:
    description: Bicep main file path
    required: true
    default: ./main.bicep
  outputFilePath:
    description: ARM template output path
    required: false
    default: ./azuredeploy.json

runs:
  using: composite
  steps:
    - run: az bicep build --file ${{ inputs.bicepFilePath }} --outfile ${{ inputs.outputFilePath }}
      shell: bash
